/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess */

#ifndef _Included_org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess
#define _Included_org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess
 * Method:    AEGetParamDesc
 * Signature: (IIILorg/eclipse/swt/internal/carbon/AEDesc;)I
 */
JNIEXPORT jint JNICALL Java_org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess_AEGetParamDesc
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess
 * Method:    getDocDir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess_getDocDir
  (JNIEnv *, jclass);

/*
 * Class:     org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess
 * Method:    memmove
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess_memmove
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess
 * Method:    initializeDriveDetection
 * Signature: (Lorg/gudy/azureus2/platform/macosx/access/jnilib/OSXDriveDetectListener;)V
 */
JNIEXPORT void JNICALL Java_org_gudy_azureus2_platform_macosx_access_jnilib_OSXAccess_initializeDriveDetection
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
